blog/urls.py
from django.urls import path
from blog import views

# It is also possible to create a namespace to each url defining app_name.
# So it will be necessary to implement it inside html references like
# blog:example
app_name = 'blog'

# Here inside blog url it is not necessary to write blog/ because it was
# already defined using the method inside() in project/urls.py
# Name parameter is configured to be used inside html as an url linking
urlpatterns = [
    path('', views.blog, name='home'),
    # it is prudent identify id type
    # URL Dispatcher
    # https://docs.djangoproject.com/en/4.2/topics/http/urls/
    # 'post/<int:id>/'
    path('<int:post_id>/', views.post, name='post'),
    path('example/', views.example, name='example')
]

home/urls.py
from django.urls import path
from home import views as home_views


# It is also possible to create a namespace to each url defining app_name.
# So it will be necessary to implement it inside html references like
# blog:example
app_name = 'home'

# Name parameter is configured to be used inside html as an url linking
urlpatterns = [
    path('', home_views.home_view, name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# About method include
# Use include method to join another endpoints to principal created here.
# For example, it is not necessary to repeat blog: blog/article/image/comment
# Using include, it is necessary just add /article/image/comment inside app
# blog.

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.data import posts
from typing import Any
from django.http import HttpRequest, Http404
import requests


# Create your views here.


def blog(request):
    # It works but is very slow
    # response = requests.get('https://jsonplaceholder.typicode.com/posts')
    # json_content = response.json()
    context = {
        # 'text': 'You are in blog page.',
        'title': 'Blog Title - ',
        'posts': posts
    }
    
    return render(
            request,
            'blog/index.html',
            context
    )


def example(request):
    context = {
        'text': 'You are in example page.',
        'title': 'Example Title - '
    }
    
    return render(
            request,
            'blog/example.html',
            context
    )


def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] | None = None
    
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post does not exist.')
    
    context = {
        'title': found_post['title'],
        'post': found_post
    }
    
    return render(
            request,
            'blog/post.html',
            context
    )

home/views.py
from django.shortcuts import render


# Create your views here.


def home_view(request):
    # To render the page home.html it is necessary to configure the app home
    # created on file settings.py > in INSTALLED_APPS array > add home that
    # is configured at apps.py of home app, HomeConfig > name
    # To prevent collision between others files named 'home.html' it is
    # important to configure namespace on templates
    # To do this it is necessary to create inside directory template another
    # directory with app name, for example, templates > home > template files
    # This strategy is named namespace, this will avoid collision between
    # equal file names.
    
    context = {
        'text': 'You are in home.',
        'title': 'Home Title - '
    }
    
    return render(
            request,
            'home/index.html',  # 'global/base.html'
            context
    )

blog/templates/blog/example.html
<!-- This block of code will use the code used on base.html as a component or inheritance -->
{% extends 'global/base.html' %}
<!-- This code block will exchange text value -->
{% block text %} BLOG EXAMPLE: {{ text }} {% endblock text %}

blog/templates/blog/index.html
<!-- This block of code will use the code used on base.html as a component or inheritance -->
{% extends 'global/base.html' %}

<!-- This code block will exchange text value -->
{% block text %} BLOG INDEX: {{ text }} {% endblock text %}

<!-- implement block posts created in base.html -->
{% block posts %}
    <!-- posts is the variable that came from context, that is in blog/views.py -->
    {% for post in posts %}
        <!-- Include postblock.html from partials -->
        <!-- now that we are using post, inside postblock will be possible to access post -->
        {% include 'global/partials/postblock.html' %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
<!-- This block of code will use the code used on base.html as a component or inheritance -->
{% extends 'global/base.html' %}

<!-- This code block will exchange text value -->
{% block text %} BLOG INDEX: {{ text }} {% endblock text %}

<!-- implement block posts created in base.html -->
{% block posts %}
    <article class="post single-post">
        <header>
            <h1 class="post__title">
                <a href="{% url 'blog:post' post.id %}">
                    {{ post.title }}
                </a>
            </h1>
        </header>

        <div class="post__body">
            {{ post.body }}
        </div>
    </article>
{% endblock posts %}

home/templates/home/index.html
<!-- This block of code will use the code used on base.html as a component or inheritance -->
{% extends 'global/base.html' %}
<!-- This code block will exchange text value -->
{% block text %} HOME INDEX: {{ text }} {% endblock text %}